package task4;

import java.util.LinkedList;

// Start of user code for imports
// End of user code

/**
 * Exam class definition.
 * Generated by the TouchCORE code generator.
 */
public class Exam {
    
    protected int courseCode;
    protected int weigth;
    protected LinkedList<Student> students;
    
    public Exam(int courseCode, int weigth) {
        
    	this.courseCode = courseCode;
    	this.weigth = weigth;
    	this.students = new LinkedList<Student>();
    }
    
    public void assign(Student s){
    	students.add(s);
    }
    
    public String toString(){
    	return "Exam for course code " + this.courseCode + " with weigth " + weigth 
    			+ " and " + students.size() + " students in it";
    }
    
    public int getCourseCode(){
    	return courseCode;
    }
    
    public String getStudents(){
    	return students.toString();
    }
}
