package task4;

// Start of user code for imports
// End of user code

/**
 * Student class definition.
 * Generated by the TouchCORE code generator.
 */
public class Student {
    
    protected String name;
    
    public Student(String name) {
        
    	this.name = name;
    }
    
    public String toString(){
    	return this.name;
    }
}
